env:
  DEVELOPER_DIR: "/Applications/Xcode.app/Contents/Developer"
  PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

steps:
  - command: "source ~/.bash_profile\n\nbundle exec fastlane ios test\nbundle exec fastlane mac test"
    label: ":rocket: Execute Test Suite"